# Generated by Django 4.2.4 on 2023-08-14 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='categories',
            new_name='category',
        ),
    ]
