# Generated by Django 4.2.4 on 2023-08-30 13:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tag',
            field=models.CharField(choices=[('Home', 'Home'), ('Shop', 'Shop'), ('Work', 'Work'), ('Fitness', 'Fitness'), ('Learning', 'Learning'), ('Other', 'Other')], default='Other', max_length=8),
        ),
        migrations.AlterField(
            model_name='list',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2023, 8, 30), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='list.list'),
        ),
    ]
