# Generated by Django 4.2.4 on 2023-08-30 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2023, 8, 30)),
        ),
        migrations.AlterField(
            model_name='list',
            name='important_event',
            field=models.BooleanField(default=False),
        ),
    ]
