# Generated by Django 4.2.4 on 2023-08-31 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_alter_list_date_alter_list_important_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='date',
            field=models.DateField(default=datetime.date(2023, 8, 31)),
        ),
    ]
