# Generated by Django 4.2.4 on 2023-09-02 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_alter_list_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='date',
            field=models.DateField(default=datetime.date(2023, 9, 2)),
        ),
    ]
