# Generated by Django 4.2.4 on 2023-09-07 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_alter_list_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='important_event',
            new_name='important_task',
        ),
        migrations.AlterField(
            model_name='list',
            name='date',
            field=models.DateField(default=datetime.date(2023, 9, 7)),
        ),
    ]
